name: transition_be_production
description: App Description
ignoreFiles: .git node_modules
modules:
- name: template
  language: nodejs18.x
  description: Module description
  functions:
  - name: entry
    entry: entry.js
    description: the entry point for the function