name: P3iD Deployment

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
  build:
    runs-on: ubuntu-20.04
    needs: unit-test
    steps:
      - uses: actions/checkout@v3
      - run: |
          cp ./.lyrid-definition.staging.yml ./.lyrid-definition.yml
      - uses: LyridInc/lyrid-deploy@v0.2.0 # This is the action
        with:
          lyrid-key: yPzpVEGHmYU26oKvLYSA
          lyrid-secret: rPzxgAAwjRYIKLGloSzsxaRhX5ooVH7T15AxXhFXd8U1Nc8GhB
          instanceid: hz2feFhV7a
